## Import Funtions from individual files.

In [1]:
from MyConfusionMatrix import *
from TrainMyClassifier import *
from MyCrossValidate import *
from TestMyClassifier import *

# To load .mat file.
import scipy.io as io

## Load training data

In [2]:
train = io.loadmat("Proj2FeatVecsSet1.mat")['Proj2FeatVecsSet1']
# label shape is [25000, 5] as [num_sample, num_class]
label = io.loadmat("Proj2TargetOutputsSet1.mat")['Proj2TargetOutputsSet1']
data = np.concatenate((train, label), axis=1)
np.random.shuffle(data)
train = data[:,:-5]
train = train[:100]
label = data[:,-5:]
label = label[:100]

## Cross validate to get estimated parameters

In [3]:
Ytrain, EstParameter, EstConfMatrices, ConfMatrix = MyCrossValidate(train, label, 5)

Searching Parameters for SVM: 100%|██████████| 36/36 [00:02<00:00, 17.81it/s]


Average cross validation score for SVM is 52.0%.
Number of support vector for validation set 0: 77
Confusion matrix for validation set 0: 
[[2 0 0 0 0 0]
 [0 0 0 4 0 3]
 [0 0 4 0 0 0]
 [0 0 0 3 0 2]
 [0 0 0 0 1 1]
 [0 0 0 0 0 0]]
Number of support vector for validation set 1: 79
Confusion matrix for validation set 1: 
[[7 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 2 0 0 1]
 [0 1 0 1 0 1]
 [0 0 0 0 4 0]
 [0 0 0 0 0 0]]
Number of support vector for validation set 2: 79
Confusion matrix for validation set 2: 
[[6 0 0 0 0 0]
 [0 0 0 3 0 1]
 [0 0 2 0 1 1]
 [0 0 0 2 0 1]
 [0 0 0 0 3 0]
 [0 0 0 0 0 0]]
Number of support vector for validation set 3: 76
Confusion matrix for validation set 3: 
[[2 0 0 0 0 0]
 [0 1 1 0 0 1]
 [1 0 2 0 0 0]
 [0 4 0 0 0 4]
 [0 0 0 0 2 2]
 [0 0 0 0 0 0]]
Number of support vector for validation set 4: 79
Confusion matrix for validation set 4: 
[[3 0 1 0 0 0]
 [0 0 0 4 0 0]
 [0 0 3 0 1 2]
 [0 0 0 3 0 1]
 [0 0 0 0 0 2]
 [0 0 0 0 0 0]]
Over all Confusion matrix for SVM: 
[[20  0  2